### PR TITLE
Lookup columns where the type is an enum array

### LINKED ISSUE #21: Support enum arrays
**Is your feature request related to a problem? Please describe.**

Having a table where a columns data type is an enum array prevents the analyzer from working.
```
create type mood as enum ('happy');
create table foo (moods mood[]);
```
causes the following warning to be thrown
> Error while connecting to the development database using the connection string from environment variable 'NPGSQL_FSHARP' or put the connection string in a file called 'NPGSQL_FSHARP' relative next your project or in your project root. Connection error: Unsupported datatype mood.

### PR DESCRIPTION
**Pull request by francesconi**
That this PR closes #21 isn't entirely true. It prevents the analyzer from stopping to work whereas there needs to be done some more changes in order to handle enum types, not just enum arrays. Please correct me if I'm wrong.
Does it make sense to you to rename this issue then close it and create a new one for enums?

### CODE REVIEW

**Comment by francesconi** [comment]
ping

**Comment by Zaid-Ajaj** [comment]
Hi there @francesconi sorry for the delayed reply I have been really busy lately, I will be looking into the issue shortly. The PR looks good for now. I will merge and publish asap when time permits. Again sorry for the delay and thanks for the PR

**Comment by Zaid-Ajaj** [comment]
Hello @francesconi, your PR merged and published as of v3.22.1 and should be available everywhere (nuget for vs code analyzers, vs extension or CLI tool via Ubik)

> there needs to be done some more changes in order to handle enum types, not just enum arrays

I am not sure we can do a lot about enums. Just like any custom types such as `ltree`, the way to work with them is cast them to something understandable by the analyzer (for example to string using `::text`) and work from there. If you have any ideas about improving the static analysis, please open an issue to discuss 😄

**Comment by francesconi** [comment]
Perfect, thank you! 🚀

**Pull request merged**
